# Generated by Django 4.1.2 on 2022-10-10 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("quantity", models.FloatField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("lb", "Pounds"),
                            ("OU", "Ounces"),
                            ("FO", "Fluid Ounces"),
                            ("L", "Liters"),
                            ("t", "Teaspoons"),
                            ("T", "Tablespoons"),
                            ("C", "Cups"),
                            ("PT", "Pints"),
                            ("QT", "Quarts"),
                            ("GAL", "Gallons"),
                            ("ML", "Milliliters"),
                            ("MG", "Milligrams"),
                            ("g", "Grams"),
                            ("kg", "Kilograms"),
                            ("OT", "Other"),
                        ],
                        default="OT",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="inventory/%Y/%m/%d"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=40)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("photo", models.ImageField(upload_to="inventory/%Y/%m/%d")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_recipes",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menuitem_recipes",
                        to="inventory.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["quantity"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_menuitems",
                        to="inventory.menuitem",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_purchases",
                        to="inventory.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["id", "slug"], name="inventory_m_id_e730d7_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["title"], name="inventory_m_title_ec5a86_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["-created"], name="inventory_m_created_199ee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(fields=["name"], name="inventory_i_name_9e7294_idx"),
        ),
        migrations.AddIndex(
            model_name="reciperequirement",
            index=models.Index(
                fields=["menu_item"], name="inventory_r_menu_it_547df4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reciperequirement",
            index=models.Index(
                fields=["ingredient"], name="inventory_r_ingredi_1c3923_idx"
            ),
        ),
    ]
