# Generated by Django 4.1.2 on 2022-10-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("quantity", models.FloatField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(max_length=200)),
                ("unit", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=2)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="inventory/%Y/%m/%d"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["id", "slug"], name="inventory_m_id_e730d7_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["title"], name="inventory_m_title_ec5a86_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["-created"], name="inventory_m_created_199ee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(fields=["name"], name="inventory_i_name_9e7294_idx"),
        ),
    ]
