# Generated by Django 4.1.2 on 2022-10-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_menuitem_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_recipes",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menuitem_recipes",
                        to="inventory.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["quantity"],
            },
        ),
        migrations.AddIndex(
            model_name="reciperequirement",
            index=models.Index(
                fields=["menu_item"], name="inventory_r_menu_it_547df4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reciperequirement",
            index=models.Index(
                fields=["ingredient"], name="inventory_r_ingredi_1c3923_idx"
            ),
        ),
    ]
